// sidebar
export const REPLACE_SHOW_PANEL_GEOVISOR = 'REPLACE_SHOW_PANEL_GEOVISOR'

// regions
export const REPLACE_REGIONS = 'REPLACE_REGIONS'
export const REPLACE_LOADING_REGIONS = 'REPLACE_LOADING_REGIONS'
export const REPLACE_LOADING_PROVINCES = 'REPLACE_LOADING_PROVINCES'
export const REPLACE_PROVINCES = 'REPLACE_PROVINCES'
export const REPLACE_LOADING_DISTRICTS = 'REPLACE_LOADING_DISTRICTS'
export const REPLACE_DISTRICTS = 'REPLACE_DISTRICTS'

// users
export const REPLACE_SHOW_MODAL_ADD_USER = 'REPLACE_SHOW_MODAL_ADD_USER'
export const REPLACE_SHOW_MODAL_EDIT_USER = 'REPLACE_SHOW_MODAL_EDIT_USER'
export const REPLACE_SHOW_MODAL_DELETE_USER = 'REPLACE_SHOW_MODAL_DELETE_USER'
export const REPLACE_USERS = 'REPLACE_USERS'
export const REPLACE_LOADING_USERS = 'REPLACE_LOADING_USERS'
export const REPLACE_USER = 'REPLACE_USER'
export const REPLACE_LOADING_USER = 'REPLACE_LOADING_USER'
export const REPLACE_SHOW_MODAL_VIEW_PENDING_REQUEST = 'REPLACE_SHOW_MODAL_VIEW_PENDING_REQUEST'
export const REPLACE_CURRENT_PENDING_REQUEST = 'REPLACE_CURRENT_PENDING_REQUEST'

// User Requests
export const REPLACE_PENDING_REQUESTS = 'REPLACE_PENDING_REQUESTS'
export const REPLACE_LOADING_PENDING_REQUESTS = 'REPLACE_LOADING_PENDING_REQUESTS'
export const REPLACE_REJECTED_REQUESTS = 'REPLACE_REJECTED_REQUESTS'
export const REPLACE_LOADING_REJECTED_REQUESTS = 'REPLACE_LOADING_REJECTED_REQUESTS'

// layer Modals
export const REPLACE_SHOW_MODAL_ADD_LAYER = 'REPLACE_SHOW_MODAL_ADD_LAYER'
export const REPLACE_SHOW_MODAL_EDIT_LAYER = 'REPLACE_SHOW_MODAL_EDIT_LAYER'
export const REPLACE_SHOW_MODAL_DELETE_LAYER = 'REPLACE_SHOW_MODAL_DELETE_LAYER'
export const REPLACE_SHOW_MODAL_ADD_BASE_MAP = 'REPLACE_SHOW_MODAL_ADD_BASE_MAP'

// base map
export const REPLACE_BASE_MAPS = 'REPLACE_BASE_MAPS'
export const REPLACE_LOADING_BASE_MAPS = 'REPLACE_LOADING_BASE_MAPS'

// services WMS Modals
export const REPLACE_SHOW_MODAL_ADD_WMS_SERVICE = 'REPLACE_SHOW_MODAL_ADD_WMS_SERVICE'
export const REPLACE_SHOW_MODAL_ADD_WMS_CATEGORY = 'REPLACE_SHOW_MODAL_ADD_WMS_CATEGORY'
export const REPLACE_SHOW_MODAL_ADD_WMS_AUTHOR = 'REPLACE_SHOW_MODAL_ADD_WMS_AUTHOR'

// services WMS
export const REPLACE_WMS_SERVICES = 'REPLACE_WMS_SERVICES'
export const REPLACE_LOADING_WMS_SERVICES = 'REPLACE_LOADING_WMS_SERVICES'

// categories WMS
export const REPLACE_WMS_CATEGORIES = 'REPLACE_WMS_CATEGORIES'
export const REPLACE_LOADING_WMS_CATEGORIES = 'REPLACE_LOADING_WMS_CATEGORIES'

// WMS authors
export const REPLACE_WMS_AUTHORS = 'REPLACE_WMS_AUTHORS'
export const REPLACE_LOADING_WMS_AUTHORS = 'REPLACE_LOADING_WMS_AUTHORS'

// report
export const REPLACE_LOADING_REPORTS = 'REPLACE_LOADING_REPORTS'
export const REPLACE_REPORTS = 'REPLACE_REPORTS'