export const REPLACE_SHOW_MODAL_ADD_USER = 'REPLACE_SHOW_MODAL_ADD_USER'
export const REPLACE_SHOW_MODAL_EDIT_USER = 'REPLACE_SHOW_MODAL_EDIT_USER'
export const REPLACE_SHOW_MODAL_DELETE_USER = 'REPLACE_SHOW_MODAL_DELETE_USER'

export const REPLACE_LOADING_REGISTERED_USER = 'REPLACE_LOADING_REGISTERED_USER'
export const REPLACE_REGISTERED_USER = 'REPLACE_REGISTERED_USER'
export const REPLACE_REGISTERED_USER_VALID = 'REPLACE_REGISTERED_USER_VALID'