// store context
export const SET_DATA_CONTEXT = 'SET_DATA_CONTEXT'
export const SET_ITEM_CONTEXT = 'SET_ITEM_CONTEXT'
export const SET_PUBLISHED_ITEM_CONTEXT = 'SET_PUBLISHED_ITEM_CONTEXT'
export const SET_CURRENT_PAGE_ON_TABLE = 'SET_CURRENT_PAGE_ON_TABLE'

export const SET_PROFILE = 'SET_PROFILE'

export const SET_SPACES = 'SET_SPACES'

// current dynamic
export const SET_DYNAMIC_MAIN_MODAL = 'SET_DYNAMIC_MAIN_MODAL'
export const SET_DYNAMIC_SECOND_MODAL = 'SET_DYNAMIC_SECOND_MODAL'
export const SET_MODAL_MAIN_FOLDER_NAME = 'SET_MODAL_MAIN_FOLDER_NAME'
export const SET_MODAL_SECOND_FOLDER_NAME = 'SET_MODAL_SECOND_FOLDER_NAME'
export const SET_MODAL_VISIBLE = 'SET_MODAL_VISIBLE'

// regions
export const SET_REGIONS = 'SET_REGIONS'
export const SET_LOADING_REGIONS = 'SET_LOADING_REGIONS'
export const SET_LOADING_PROVINCES = 'SET_LOADING_PROVINCES'
export const SET_PROVINCES = 'SET_PROVINCES'
export const SET_LOADING_DISTRICTS = 'SET_LOADING_DISTRICTS'
export const SET_DISTRICTS = 'SET_DISTRICTS'

// modals
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

// spinners
export const ENABLE_SPINNER = 'ENABLE_SPINNER'
export const DISABLE_SPINNER = 'DISABLE_SPINNER'

//structure tree group layers
export const SET_STRUCTURE_TREE = 'SET_STRUCTURE_TREE'
