// sidebar
export const REPLACE_SHOW_PANEL_GEOVISOR = 'REPLACE_SHOW_PANEL_GEOVISOR'

// users
export const REPLACE_SHOW_MODAL_ADD_USER = 'REPLACE_SHOW_MODAL_ADD_USER'
export const REPLACE_SHOW_MODAL_EDIT_USER = 'REPLACE_SHOW_MODAL_EDIT_USER'
export const REPLACE_SHOW_MODAL_DELETE_USER = 'REPLACE_SHOW_MODAL_DELETE_USER'
export const REPLACE_USERS = 'REPLACE_USERS'
export const REPLACE_LOADING_USERS = 'REPLACE_LOADING_USERS'

// layer
export const REPLACE_SHOW_MODAL_ADD_LAYER = 'REPLACE_SHOW_MODAL_ADD_LAYER'
export const REPLACE_SHOW_MODAL_EDIT_LAYER = 'REPLACE_SHOW_MODAL_EDIT_LAYER'
export const REPLACE_SHOW_MODAL_DELETE_LAYER = 'REPLACE_SHOW_MODAL_DELETE_LAYER'
export const REPLACE_SHOW_MODAL_ADD_BASE_MAP = 'REPLACE_SHOW_MODAL_ADD_BASE_MAP'

//base map
export const REPLACE_BASE_MAPS = 'REPLACE_BASE_MAPS'
export const REPLACE_LOADING_BASE_MAPS = 'REPLACE_LOADING_BASE_MAPS'

// regions
export const REPLACE_REGIONS = 'REPLACE_REGIONS'
export const REPLACE_LOADING_REGIONS = 'REPLACE_LOADING_REGIONS'
export const REPLACE_LOADING_PROVINCES = 'REPLACE_LOADING_PROVINCES'
export const REPLACE_PROVINCES = 'REPLACE_PROVINCES'
export const REPLACE_LOADING_DISTRICTS = 'REPLACE_LOADING_DISTRICTS'
export const REPLACE_DISTRICTS = 'REPLACE_DISTRICTS'