export const BASE_LAYER = '/base_layer'
export const VECTORIAL_LAYER = '/vectorial_layer'
export const RASTER_LAYER = '/raster_layer'
export const GROUP_LAYER = '/group_layer'
export const GEOREFERENCED_IMAGE = '/georeferenced_image'
